[tool.ruff]

[tool.ruff.lint]
ignore = ["E501"]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C4", # Ruff's docstring conventions
    "NPY", # Ruff's NumPy conventions
    "PD", # Ruff's Pandas conventions
    "SIM", # Ruff's simplifications
    "TCH", # Ruff's type checking
]

[tool.ruff.format]
docstring-code-line-length = 300